version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./symfony-task:/var/www
      - ./plain-tasks:/var/plain
    networks:
      - network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./symfony-task:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network

  db:
    image: mysql:8.0.28
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  dbdata:
    driver: local