lexik_jwt_authentication:
  secret_key: '%kernel.project_dir%/app/config/jwt/private.pem'
  public_key: '%kernel.project_dir%/app/config/jwt/public.pem'
  pass_phrase: '%jwt_secret%'
  token_ttl: 3600

security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt

  providers:
    app:
      entity:
        class: AppBundle:User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_v1:
      stateless: true
      anonymous: true
      provider: app
      json_login:
        check_path: api_v1_login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/v1/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/v1/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
