parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Modules\Api\V1\Controller\:
        resource: '../../src/AppBundle/Modules/Api/V1/Controller'
        public: true
        tags: ['controller.service_arguments']
